// Define os tokens básicos da linguagem scheme
// string, identificadores e números podem em teoria ser definidos aqui
// Ou podemos usar a recursão da linguagem no bison.
typedef enum token_type{ 
    // Delimitadores
    L_PAREN,
    R_PAREN,
    BACKSLASH,
    STRING_DELIMITER,
    LITERAL_DELIMITER,
    COMMA,
    SEMICOLON,
    MULTILINE_COMMENT_START,
    MULTILINE_COMMENT_END,

    // Palavras Reservadas
    DEFINE,
    DEFINE_VALUES,
    DEFINE_RECORD_TYPE,
    BEGIN,
    LAMBDA,
    COND,
    CASE,
    IF,
    ELSE,
    AND,
    OR,
    WHEN,
    UNLESS,
    LET,
    LETREC,
    LET_VALUES,
    LET_SYNTAX,
    LETREC_SYNTAX,
    BEGIN,
    DO,
    DELAY,
    DELAY_FORCE,
    PARAMETRIZE,
    GUARD,
    CASE_LAMBDA,
    EXPORT,
    RENAME,
    COND_EXPAND,
    IMPORT,
    INCLUDE_LIBRARY_DECLARATIONS,
    ONLY,
    EXCEPT,
    PREFIX,
    NOT,
    LOOP,
    EQ,
    CONS,
    SET,

    // Symbols
    MULT,
    PLUS,
    MINUS,
    ASSIGN,
    TRUE,
    FALSE,
    VERTICAL_LINE,
    EQUAL_SIGN,
    LEFT_ARROW,
    RIGHT_ARROW,
    COLON,
    PERCENT,
    DOLLAR,
    AMPERSAND,
    INTERROGATION,
    UNDERLINE,
    POINT,
    DIGIT,
    LETTER,

    // Prefixes
    CHARACTER_CONSTANT,
    VECTOR_CONSTANT_START,
    BYTE_VECTOR_CONSTANTE_START,
    DIRECTIVE_START,
    BASE_2_INDICATOR,
    BASE_8_INDICATOR,
    BASE_16_INDICATOR,
    BASE_10_INDICATOR,
    E_INDICATOR,
    I_INDICATOR,
} TokenType;